Repository HackBadgers/MovieBadgers, pull requests merged in 2020-09, with the labels that each got.

#2 settings: create .gitignore
  .gitignore
Labels: settings

#6 feature: create a initial project using flutter
  movie_badgers/.gitignore
  movie_badgers/.metadata
  movie_badgers/README.md
  movie_badgers/android/.gitignore
  movie_badgers/android/app/build.gradle
  movie_badgers/android/app/src/debug/AndroidManifest.xml
  movie_badgers/android/app/src/main/AndroidManifest.xml
  movie_badgers/android/app/src/main/kotlin/com/hackbadgers/moviebadgers/MainActivity.kt
  movie_badgers/android/app/src/main/res/drawable/launch_background.xml
  movie_badgers/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  movie_badgers/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  movie_badgers/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  movie_badgers/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  movie_badgers/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  movie_badgers/android/app/src/main/res/values/styles.xml
  movie_badgers/android/app/src/profile/AndroidManifest.xml
  movie_badgers/android/build.gradle
  movie_badgers/android/gradle.properties
  movie_badgers/android/gradle/wrapper/gradle-wrapper.properties
  movie_badgers/android/settings.gradle
  movie_badgers/ios/.gitignore
  movie_badgers/ios/Flutter/AppFrameworkInfo.plist
  movie_badgers/ios/Flutter/Debug.xcconfig
  movie_badgers/ios/Flutter/Release.xcconfig
  movie_badgers/ios/Runner.xcodeproj/project.pbxproj
  movie_badgers/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  movie_badgers/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  movie_badgers/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  movie_badgers/ios/Runner.xcworkspace/contents.xcworkspacedata
  movie_badgers/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  movie_badgers/ios/Runner/AppDelegate.swift
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  movie_badgers/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  movie_badgers/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  movie_badgers/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  movie_badgers/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  movie_badgers/ios/Runner/Base.lproj/LaunchScreen.storyboard
  movie_badgers/ios/Runner/Base.lproj/Main.storyboard
  movie_badgers/ios/Runner/Info.plist
  movie_badgers/ios/Runner/Runner-Bridging-Header.h
  movie_badgers/lib/main.dart
  movie_badgers/lib/modules/home/view/pages/home_page.dart
  movie_badgers/pubspec.yaml
Labels: feature

#8 feature: setup of dart lint
  movie_badgers/analysis_options.yaml
  movie_badgers/pubspec.yaml
Labels: feature

#9 docs: naming patterns for branches and commits
  README.md
Labels: documentation
